### ISSUE TITLE
Refactor + new features

### ISSUE THREAD

**Issue by tg44** [ticofab/reactive-kraken#12]
Hy!

I start to work on this codebase, and if you want to, I will PR my modifications.

I made a quick tour in the code, and I want to make some changes like;
- Split the Kraken actor to public and private part (so we can ratelimit the private requests in the future).
- After the split the it tests from the public part can get a new spec (and can be run without api keys)
- I want to make some object/companion-object reorganization too (mostly for the smaller case-classes)
- I didn't run throught the whole code, but I want to implement all the public api (I have no idea if there are missing ones or not, but I want to cover it)
- I want to implement trade history (the reason I wanted to find a lib at the beginning :D )
- Implement a throttler actor for the private request what can count the rate limits, and hold requests if needed

These will cover some of the already opened issues. I thought about to just solve them, but at the beginning I want to split your main actor.

**Comment by ticofab** [comment]
Hey @tg44 - thanks for opening this issue! I'll be very happy to see your PRs and merge them!
About your points, all good ideas. I am just not sure what you mean with "I want to implement trade history" ?

**Comment by tg44** [comment]
https://www.kraken.com/help/api#get-trades-history   This one.

**Comment by ticofab** [comment]
Ah yeah perfect!

**Comment by tg44** [comment]
Pr added.

CouldBeBetter section:
It would be nice if the Long, String, Double responses would be handled as is (and not as the api give back the data) (for ex. price is handled as string, the time came back all the possible formats and so on)
I would recommend to remove all the headers from the files, and remove the other "documentation" from the code.
The JsonSupport starts to reach an unmanageable size.
I would move the other Model case-classes to the companion object too. (Or at least asset, assetpair, ticker and tradebalance.)
RecentTradeRow could use enums instead of strings.


I start the private api implementation on a separated branch originated from that pr. I will go to the "cover all the api" direction, and in the second pass I will make it actually usable. If you have any suggestion don't be shy :D
