### ISSUE TITLE
Get Ledgers Info

### ISSUE THREAD

**Issue by rayohan** [ticofab/reactive-kraken#14]
Hi. First, thanks for your code base. 
It was really helpful!!
I am doing a extension from your code for obtain the "Get ledgers info" of Kraken api.
But i have some troubles with the Json Parser and Akka implement.
Did you implement that process?

https://www.kraken.com/help/api#get-ledgers-info

**Comment by ticofab** [comment]
Hey @rayohan , thanks for willing to contribute. What causes you trouble exactly?

**Comment by rayohan** [comment]
Thanks for the quick reply, I am new programming scala so I really appreciate your help.

I have studied your code and I have relied on it to make the solution for the method "Get ledgers info".

I have done this:

**1- Create a class in the model directory:**
case class Ledger(aclassLedger: String, refIdLedger: String, balanceLedger: String, amountLedger: String, timeLedger: Double, assetLedger: String, typeLedger: String, feeLedger: String)

**2- Create "GetCurrentLedger method, GetCurrentLedger object and CurrentLedger class" in KrakenPrivateApiActor:**

**a)**
   case GetCurrentLedger=>
   val path = "/0/private/Ledgers"
   val responseFunction = (request: HttpRequest) => handleRequest[Map[String, Ledger]](request)
           .map(extractMessage[Map[String, Ledger], CurrentLedger, Map[String, Ledger]](_, CurrentLedger, 
   _.result.get))
          getAuthenticatedAPIResponseMessage(credentials, path, responseFunction).pipeTo(sender)
**b)**
    case object GetCurrentLedger extends Message
**c)**
    case class CurrentLedger(result: Either[List[String], Map[String, Ledger]]) extends MessageResponse

**3- Create method in JsonSupport: <--- MY TROUBLE! (I try 2 methods)**

**a)**  implicit val LedgerFormat = jsonFormat(Ledger, "aclass", "refid", "balance", "amount", "time", "asset", "type", "fee")

With this, when i run the test i recive the following:
CurrentLedger(Left(List(Object is missing required member 'aclass')))

**b)**   implicit val ledgerRowFormat = new JsonFormat[Ledger] {
    type LedgerRowTuple = Tuple8[String, String, String, String, Double, String, String, String]
    override def read(js: JsValue) = {
      Ledger.tupled(js.convertTo[LedgerRowTuple])
    }
    override def write(obj: Ledger) = Ledger.unapply(obj).get.toJson
  }

With this, when i run the test i recive the following:
CurrentLedger(Left(List(Expected Tuple8 as JsArray, but got {"**Here I am shown the data** "}

**Thanks for your time!**

**Comment by tg44** [comment]
I think the problem probably with the test. The Tuple8 as JsArrat but got {""} seems like your test data is not a wellformed or valid json. The object is missing required member is mostly happens at the same reason (you want to get a field from an JsObject, but the object has not that field).

**Comment by rayohan** [comment]
> I think the problem probably with the test. The Tuple8 as JsArrat but got {""} seems like your test data is not a wellformed or valid json. The object is missing required member is mostly happens at the same reason (you want to get a field from an JsObject, but the object has not that field).

**Thanks for the reply!**

I see your point, i will review it, but meanwhile:

I think that the exception that i pick comes from this method in the "JsonSupoort":

  implicit def tuple8Format[A :JsonFormat, B :JsonFormat, C :JsonFormat, D :JsonFormat, E :JsonFormat, F: JsonFormat, G: JsonFormat, H:JsonFormat] = {
    new RootJsonFormat[(A, B, C, D, E, F, G, H)] {
      def write(t: (A, B, C, D, E, F, G, H)) = JsArray(t._1.toJson, t._2.toJson, t._3.toJson, t._4.toJson, t._5.toJson, t._6.toJson, t._7.toJson, t._8.toJson)
      def read(value: JsValue) = value match {
        case JsArray(Seq(a, b, c, d, e, f, g, h)) =>
          (a.convertTo[A], b.convertTo[B], c.convertTo[C], d.convertTo[D], e.convertTo[E], f.convertTo[F], g.convertTo[G], h.convertTo[H])
        **case x => deserializationError("Expected Tuple8 as JsArray, but got " + x)**
      }
    }
  }

I think that the answer of my request to the api goes through that method, because what the test prints is that exception ("case x")

what do you think?

**Comment by rayohan** [comment]
The last thing that comes to my mind is that it is necesarry do the correct input in the "GetCurrentLedger":

**How would you include the input parameters?**
https://www.kraken.com/help/api#get-ledgers-info

Some like this?: 
      val params = asset.flatMap(value => Some(Map("asset" -> value, "aclass" -> aclass)))

**Comment by rayohan** [comment]
**I got it!!
In a while I upload the solution for you to validate it and in case someone needs it :)**

**Comment by ticofab** [comment]
Good stuff, looking forward to the pull request :)

**Comment by rayohan** [comment]
Hi! I have not done the commit yet beacuse i can't resolve another issue.
The code for obtain the info of LedgersInfo works fine, but only without parameters in the input.
When I try do it with input parameters I obtain a "EGeneral:Invalid arguments".

I try do the same with other methods like TradeBalance with asset in the input and I obtain the same result -> "EGeneral:Invalid arguments".

Any idea?

When I resolve this I do the pull ;)
