### ISSUE TITLE
Make interval customisable but with enums

### ISSUE THREAD

**Issue by ticofab** [ticofab/reactive-kraken#7]
It should be something like "ONE_SECOND", "THREE_SECONDS", "FIVE_SECONDS" and so on.
Let's start with a minimum interval of one second.

**Comment by tg44** [comment]
Why? We have finiteDuration for this. Writing down 5.seconds is more common if you ask me.

**Comment by ticofab** [comment]
Because I only want to allow for specific intervals to be chosen by the user of the library. For instance, I don't want anyone to set the refresh interval as `2.milliseconds`.

**Comment by tg44** [comment]
Ahh I see. But you could write "require"s to them like require(delay > 1 seconds)
